sudo: false
dist: trusty
language: rust
rust: nightly-2019-05-09 # minimum required version for async/await

before_install:
  - cargo install mdbook --vers '0.2.3' --debug --force
  - cargo install mdbook-linkcheck --vers '0.2.4' --debug --force

script:
  - mdbook build
  - cargo test --all --manifest-path=./examples/Cargo.toml

env:
  RUSTINFRA_DEPLOY_DIR: book
import:
  - rust-lang/simpleinfra/travis-configs/static-websites.yml
